service: zzip-backend
frameworkVersion: '3'

provider:
  iam:
    role: DefaultRole
  httpApi:
    cors: true
    authorizers:
      zzipAuthorizer:
        type: request
        functionName: auth_authorizer
        identitySource: $request.header.Authorization
        enableSimpleResponses: true
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stage: dev
  environment:
    STAGE: ${env:STAGE, "dev"}
    JWT_SECRET_KEY: ${ssm:/${self:service}/${env:STAGE, "dev"}/jwt_secret_key}
    NAVER_CLIENT_SECRET: ${ssm:/${self:service}/${env:STAGE, "dev"}/naver_client_secret}
    OCR_SECRET_KEY: ${ssm:/${self:service}/${env:STAGE, "dev"}/ocr_secret_key}

custom:
  esbuild:
    sourcemap: true

resources:
  Resources:
    DefaultRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${env:STAGE, "dev"}-LambdaExcutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - rds-db:connect
                    - logs:*
                    - athena:*
                    - ssm:*
                    - execute-api:*
                    - secretsmanager:*
                    - lambda:*
                    - sns:*
                    - sqs:*
                  Resource: '*'

functions:
  hello:
    handler: build/hello/get.handler
    events:
      - httpApi:
          path: /hello
          method: get
  auth_authorizer:
    handler: build/auth/authorizer.handler
    events: []
  signin_apple_post:
    handler: build/signin/apple/post.handler
    events:
      - httpApi:
          path: /signin/apple
          method: post
  signin_naver_post:
    handler: build/signin/naver/post.handler
    events:
      - httpApi:
          path: /signin/naver
          method: post
  signin_kakao_post:
    handler: build/signin/kakao/post.handler
    events:
      - httpApi:
          path: /signin/kakao
          method: post
  signin_google_post:
    handler: build/signin/google/post.handler
    events:
      - httpApi:
          path: /signin/google
          method: post
  token_access_get:
    handler: build/token/access/get.handler
    events:
      - httpApi:
          path: /token/access
          method: get
  token_refresh_delete:
    handler: build/token/refresh/delete.handler
    events:
      - httpApi:
          path: /token/refresh
          method: delete
          authorizer: zzipAuthorizer
  user_get:
    handler: build/user/get.handler
    events:
      - httpApi:
          path: /user
          method: get
          authorizer: zzipAuthorizer
  user_put:
    handler: build/user/put.handler
    events:
      - httpApi:
          path: /user
          method: put
          authorizer: zzipAuthorizer
  user_delete:
    handler: build/user/delete.handler
    events:
      - httpApi:
          path: /user
          method: delete
          authorizer: zzipAuthorizer
  follow_post:
    handler: build/follow/post.handler
    events:
      - httpApi:
          path: /follow
          method: post
          authorizer: zzipAuthorizer
  follow_delete:
    handler: build/follow/delete.handler
    events:
      - httpApi:
          path: /follow
          method: delete
          authorizer: zzipAuthorizer
  follow_get:
    handler: build/follow/get.handler
    events:
      - httpApi:
          path: /follow
          method: get
          authorizer: zzipAuthorizer
  calendar_post_post:
    handler: build/calendar/post/post.handler
    events:
      - httpApi:
          path: /calendar/post
          method: post
          authorizer: zzipAuthorizer
  calendar_post_get:
    handler: build/calendar/post/get.handler
    events:
      - httpApi:
          path: /calendar/post
          method: get
          authorizer: zzipAuthorizer
  calendar_post_ocr_get:
    handler: build/calendar/post/ocr/get.handler
    events:
      - httpApi:
          path: /calendar/post/ocr
          method: get
          authorizer: zzipAuthorizer
  calendar_post_put:
    handler: build/calendar/post/put.handler
    events:
      - httpApi:
          path: /calendar/post
          method: put
          authorizer: zzipAuthorizer
  calendar_post_delete:
    handler: build/calendar/post/delete.handler
    events:
      - httpApi:
          path: /calendar/post
          method: delete
          authorizer: zzipAuthorizer
  calendar_get:
    handler: build/calendar/get.handler
    events:
      - httpApi:
          path: /calendar
          method: get
          authorizer: zzipAuthorizer
